name: First option
on:
  pull_request:
    types: [opened, edited, reopened]
  push:

defaults:
  run:
    shell: pwsh

jobs:
  build_node:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Print workflow event
      run: |
        Write-Host "Event is ${{ github.event_name }}"