name: First option
on:
  pull_request:
    types: [opened, edited, reopened]
    paths-ignore:
    - 'versions-manifest.json'
    - 'LICENSE'
    - '**.md'
    branches:
    - 'main'
  push:
    paths-ignore:
    - 'versions-manifest.json'
    - 'LICENSE'
    - '**.md'
    branches:
    - 'main'

defaults:
  run:
    shell: pwsh

jobs:
  build_node:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Print workflow event
      run: |
        Write-Host "Event is ${{ github.event_name }}"